disabled_rules:
    - trailing_whitespace
    - type_name
    - inclusive_language

opt_in_rules:
    - vertical_whitespace_closing_braces
    - vertical_parameter_alignment_on_call
    - empty_count
    - empty_string
    - empty_xctest_method
    - private_action
    - private_outlet
    - closure_end_indentation
    - closure_spacing
    - operator_usage_whitespace
    - explicit_init
    - fatal_error_message
    - force_unwrapping
    - conditional_returns_on_newline
    
warning_threshold: 1
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
  
excluded:
    - Pods

identifier_name:
  min_length:
    warning: 0

line_length:
    warning: 155
    error: 200
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
nesting:
  type_level:
    warning: 3 
